const fs = require('fs');
const path = require('path');

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

const configContent = `// Auto-generated by build.js — do not edit manually
export const CONFIG = {
  SUPABASE_URL: '${SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}'
};
`;

const outPath = path.join(__dirname, 'js', 'config.js');
fs.writeFileSync(outPath, configContent, 'utf-8');
console.log(`[build] js/config.js written (URL=${SUPABASE_URL ? 'set' : 'empty'})`);
